name: Pegaso
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #esc_pos_bluetooth:
 
  #esc_pos_utils:   
  image:  
  archive:
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  bottom_navy_bar: ^6.0.0
  fluttertoast:
  flutter_typeahead: ^3.2.0
  faker: ^2.0.0-rc.2 
  sqflite:
  autocomplete_textfield: ^1.7.3
  image_picker: ^0.8.4+4
  esc_pos_bluetooth: 
  flutter_bluetooth_basic: 
  ##esc_pos_bluetooth: ^0.4.1
  ##flutter_bluetooth_basic: ^0.1.7
  syncfusion_flutter_pdf: ^19.3.48-beta
  path_provider: ^2.0.1
  open_file: ^3.1.0
  vibration: ^1.7.3
  decorative_app_bar: ^0.0.2 
  url_launcher: ^6.1.2
  #dio: ^5.3.3

 
  #esc_pos_bluetooth: ^0.2.8
  #esc_pos_utils: ^0.3.6
 
  #image: ^2.1.4
  #permission_handler: ^8.2.5
 
 

dev_dependencies:
 #flutter_test:
 #   sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/logoapp.png"   
#dependency_overrides:
  intl: 0.17.0
  http:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/
    - assets/pegasologo.png
    - assets/data.json
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

analyzer:
  enable-experiment:
  - non-nullable